modLoader="javafml"
loaderVersion="${loader_range}"
license="${mod_license}"
showAsResourcePack=false

[[mods]]
  modId="${mod_id}"
  version="${mod_version}"
  displayName="${mod_name}"
  updateJSONURL=""
  displayURL="https://www.curseforge.com/minecraft/mc-mods/music-triggers"
  logoFile="logo.png"
  credits="${mod_author}"
  authors="${mod_author}"
  description="${mod_description}"

  [[dependencies.musictriggers]]
    modId="forge"
    mandatory=true
    versionRange="${loader_range}"
    ordering="NONE"
    side="BOTH"

  [[dependencies.musictriggers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

  [[dependencies.musictriggers]]
    modId="theimpossiblelibrary"
    mandatory=true
    versionRange="${til_range}"
    ordering="NONE"
    side="BOTH"